apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: escalate-privileges
  namespace: privilege-escalation-demo
subjects:
- kind: ServiceAccount
  name: default
  namespace: privilege-escalation-demo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
